# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf5148f78c04689dc5281c7c6174c83ddb494182eb9de64ab1dec56720892bc28adbd02dd489f3e84b44d688665bb6eaf06735c55519d00e21aa57b5e8982c31

test:
  secret_key_base: b936d2defbad5b5b171c62364846f39c45bb2ba5907d8da18c96f6046fb87dd0367e62961ca28b1e4bc879ac87f660f1db8130bfff0c832d942f552eff9b7881

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
